FROM ruby:3.3.0-slim

RUN apt-get update -qq && apt-get install --no-install-recommends -y git
RUN apt-get install --no-install-recommends -y openssl gcc make g++

ADD . /Sinatra-Docker
WORKDIR /Sinatra-Docker
RUN gem install eventmachine -- --with-cppflags=-I/usr/include/openssl
RUN bundle install

EXPOSE 4567

CMD ["/bin/bash"]
