version: "3.8"
services:
  app:
    build: .
    image: sinatra-docker-app:alpine-3.3.0-ms
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    ports:
      - "4567:4567"
    volumes:
      - .:/Sinatra-Docker
