FROM ruby:3.3.0-alpine AS build

# Dockerfile
ENV PATH="${PATH}:/sbin"

RUN apk add git gcc make g++ bash

WORKDIR /Sinatra-Docker
COPY Gemfile .
RUN gem install eventmachine -- --with-cppflags=-I/usr/include/openssl
RUN bundle install

FROM ruby:3.3.0-alpine 

ENV PATH="${PATH}:/sbin"

RUN apk add bash

COPY --from=build /usr/local /usr/local

COPY . /Sinatra-Docker

WORKDIR /Sinatra-Docker

EXPOSE 4567

CMD ["/bin/bash"]




