FROM ruby:3.3.0-alpine

ENV PATH="${PATH}:/sbin"

RUN apk add git gcc make g++ bash

ADD . /Sinatra-Docker
WORKDIR /Sinatra-Docker
RUN bundle install
RUN apk del gcc g++

EXPOSE 4567

CMD ["/bin/bash"]
